import json, pathlib
root=pathlib.Path('apprepo20260906/content/lessons')
M={
'bai-23': [('Mở rộng phân số','Nhân cả tử và mẫu với cùng một số tự nhiên khác 0 thì được phân số bằng phân số ban đầu.','Ví dụ: 1/2 = 3/6 vì chia chiếc bánh thành nhiều phần hơn nhưng phần đã ăn không đổi.','fraction'),('Phân số bằng nhau','Hai phân số bằng nhau khi chúng biểu diễn cùng một số; có thể kiểm tra bằng phép nhân chéo.','2/3 = 4/6 vì 2×6 = 3×4.','fraction')],
'bai-24':[('So sánh phân số','Đưa hai phân số về cùng mẫu dương rồi so sánh tử; tử lớn hơn thì phân số lớn hơn.','So sánh lượng nước 3/4 lít và 2/3 lít bằng cách quy về mẫu 12.','fraction'),('Hỗn số dương','Hỗn số gồm phần nguyên và phần phân số bé hơn 1; đổi hỗn số a b/c thành (a×c+b)/c.','2 1/3 nghĩa là 2 chiếc bánh nguyên và thêm 1/3 chiếc.','fraction')],
'bai-25':[('Cộng, trừ phân số','Cùng mẫu: cộng hoặc trừ các tử và giữ mẫu. Khác mẫu: quy đồng trước; cuối cùng rút gọn.','Cộng 1/4 giờ với 1/2 giờ để biết tổng thời gian đọc sách.','fraction')],
'bai-26':[('Nhân phân số','Nhân tử với tử, mẫu với mẫu rồi rút gọn.','Một nửa của 3/4 là 1/2×3/4=3/8.','fraction'),('Chia phân số','Chia cho một phân số là nhân với phân số nghịch đảo của nó.','Có 3/4 kg gạo, mỗi túi 1/8 kg thì có 6 túi.','fraction')],
'bai-27':[('Tìm giá trị phân số của một số','Muốn tìm m/n của số a, tính a×m/n.','Tìm 2/5 của 30 quả cam: 30×2/5=12 quả.','fraction'),('Tìm một số biết giá trị phân số','Nếu m/n của x bằng b thì x=b:m/n.','3/4 quãng đường là 9 km, cả quãng đường là 9:3/4=12 km.','fraction')],
'bai-28':[('Số thập phân','Phân số thập phân có mẫu 10,100,1000… viết được dưới dạng số thập phân.','0,25 m là 25 cm; dấu phẩy tách phần nguyên và phần thập phân.','decimal'),('Số đối','Hai số đối nhau có tổng bằng 0; số đối của a là -a.','Nhiệt độ 3°C và -3°C cách 0 như nhau nhưng ở hai phía.','line')],
'bai-29':[('Cộng, trừ số thập phân','Đặt các dấu phẩy thẳng cột rồi cộng hoặc trừ như số tự nhiên.','Tính tiền 12,5 nghìn + 7,25 nghìn đồng.','decimal'),('Nhân, chia số thập phân','Nhân như số tự nhiên rồi đặt dấu phẩy; chia cho 10,100… dịch dấu phẩy sang trái.','Đổi 2,5 kg thành 2500 g bằng cách nhân 1000.','decimal')],
'bai-30':[('Làm tròn số','Giữ đến hàng cần làm tròn; nhìn chữ số ngay bên phải: 0–4 giữ nguyên, 5–9 tăng 1.','3,146 làm tròn đến hàng phần trăm là 3,15.','decimal'),('Ước lượng','Ước lượng giúp tính nhanh và kiểm tra kết quả có hợp lí không.','19,8×5,1 gần bằng 20×5=100.','bar')],
'bai-31':[('Tỉ số','Tỉ số của a và b (b khác 0) là a/b; hai đại lượng phải cùng loại đơn vị khi so sánh.','Lớp có 12 bạn nữ và 18 bạn nam: tỉ số nữ:nam là 2:3.','fraction'),('Tỉ số phần trăm','Tỉ số phần trăm là tỉ số viết dưới dạng phần trăm; 1%=1/100.','15 trên 20 bạn hoàn thành tương ứng 75%.','bar')],
'bai-32':[('Điểm','Điểm là hình cơ bản, thường kí hiệu bằng chữ in hoa A, B, C.','Một vị trí trên bản đồ được đánh dấu bằng một điểm.','line'),('Đường thẳng','Đường thẳng kéo dài mãi về hai phía; qua hai điểm phân biệt chỉ có một đường thẳng.','Dùng thước nối hai vị trí để tạo đường thẳng AB.','line')],
'bai-33':[('Điểm nằm giữa hai điểm','B nằm giữa A và C khi A,B,C cùng thuộc một đường thẳng và tia BA, BC ngược nhau.','Cột mốc B nằm trên đoạn đường giữa A và C.','line'),('Tia','Tia có một gốc và kéo dài mãi về một phía; tia AB bắt đầu từ A đi qua B.','Tia nắng đi từ Mặt Trời tới một điểm.','line')],
'bai-34':[('Đoạn thẳng','Đoạn thẳng AB gồm hai đầu mút A,B và mọi điểm nằm giữa chúng.','Cạnh thước là một đoạn thẳng hữu hạn.','line'),('Độ dài đoạn thẳng','Độ dài AB là khoảng cách giữa A và B; nếu M nằm giữa A,B thì AB=AM+MB.','Đo một đoạn dây bằng thước và ghi đơn vị cm.','line')],
'bai-35':[('Trung điểm đoạn thẳng','M là trung điểm AB khi M nằm giữa A,B và MA=MB; khi đó MA=MB=AB/2.','Điểm giữa của thanh dài 10 cm cách mỗi đầu 5 cm.','line')],
'bai-36':[('Góc','Góc tạo bởi hai tia chung gốc; gốc là đỉnh, hai tia là cạnh. Kí hiệu ∠xOy.','Cánh cửa mở tạo thành một góc tại bản lề.','line'),('Góc bẹt','Hai cạnh là hai tia đối nhau thì tạo góc bẹt.','Một đường thẳng tạo góc bẹt 180°.','line')],
'bai-37':[('Số đo góc','Số đo góc cho biết độ mở, đơn vị độ (°); góc có thể đo bằng thước đo góc.','Góc 90° giống góc ở góc bàn.','line'),('Các loại góc','Góc nhọn <90°, góc vuông =90°, góc tù giữa 90° và 180°, góc bẹt =180°.','So sánh độ mở của kéo, quyển vở và góc tường.','line')],
'bai-38':[('Dữ liệu','Dữ liệu là thông tin thu được từ quan sát, đo lường hoặc điều tra.','Chiều cao của các bạn là dữ liệu số; màu yêu thích là dữ liệu phân loại.','bar'),('Thu thập dữ liệu','Có thể hỏi, quan sát, đo hoặc tra cứu; cần ghi rõ đối tượng và đơn vị.','Khảo sát phương tiện đi học của lớp.','bar')],
'bai-39':[('Bảng thống kê','Bảng thống kê sắp xếp dữ liệu thành hàng, cột; tần số là số lần xuất hiện.','Đếm số bạn chọn từng loại trái cây.','bar'),('Biểu đồ tranh','Mỗi hình biểu diễn một số lượng nhất định; cần đọc chú giải.','Một hình quả táo có thể đại diện cho 2 bạn.','bar')],
'bai-40':[('Biểu đồ cột','Biểu đồ cột dùng các cột có cùng bề rộng, chiều cao biểu diễn số liệu; trục và đơn vị phải rõ.','Cột cao hơn nghĩa là số lượng lớn hơn.','bar')],
'bai-41':[('Biểu đồ cột kép','Biểu đồ cột kép đặt hai cột cạnh nhau cho mỗi đối tượng để so sánh hai nhóm dữ liệu.','So sánh số nam và nữ tham gia các môn thể thao.','bar')],
'bai-42':[('Kết quả có thể','Trong trò chơi/thí nghiệm, tập hợp các kết quả có thể xảy ra cần được liệt kê.','Tung xúc xắc có các kết quả 1,2,3,4,5,6.','bar'),('Sự kiện','Sự kiện là một hoặc nhiều kết quả; sự kiện chắc chắn luôn xảy ra, không thể không xảy ra.','Ra số chẵn khi tung xúc xắc là sự kiện gồm 2,4,6.','bar')],
'bai-43':[('Xác suất thực nghiệm','Xác suất thực nghiệm của sự kiện bằng số lần sự kiện xảy ra chia cho tổng số lần thử.','Tung đồng xu 50 lần, xuất hiện ngửa 27 lần thì xác suất thực nghiệm là 27/50.','bar')]
}
for f,cs in M.items():
 p=root/(f+'.json'); d=json.loads(p.read_text(encoding='utf-8-sig'))
 d['concepts']=[{'id':f'c{i+1}','title':t,'explanation':e,'example':ex,'visual':v} for i,(t,e,ex,v) in enumerate(cs)]
 d['theory']=[{'id':f'q{i+1}','prompt':f'Câu {i+1}: {cs[i%len(cs)][0]}. Hãy giải thích, nêu quy tắc hoặc thực hiện một ví dụ cụ thể và kiểm tra kết quả.','source':f'SGK Toán 6 Kết nối tri thức, {d.get("pages","")}', 'objectiveId':f'c{(i%len(cs))+1}'} for i in range(15)]
 d['written']=[{'id':f'w{i+1}','prompt':f'Câu tự luận {i+1}: Một bài toán thực tế về “{cs[i%len(cs)][0]}”. Hãy trình bày dữ kiện, cách làm, phép tính và kết luận bằng câu đầy đủ.','source':f'SGK Toán 6 Kết nối tri thức, {d.get("pages","")}', 'objectiveId':f'c{(i%len(cs))+1}'} for i in range(10)]
 d['textbook']=[{'page':d.get('pages',''),'note':'Nội dung và thuật ngữ được đối chiếu theo bài trong SGK.'}]
 p.write_text(json.dumps(d,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
